### ISSUE TITLE
when set padding to the recycler view 

### ISSUE THREAD

**Issue by anasanasanas** [bleeding182/recyclerviewItemDecorations#7]
![issue](https://user-images.githubusercontent.com/3528063/37491985-386c5852-28a8-11e8-8b43-162673d7a4bb.png)
issue when setting padding to the recycler view

**Comment by bleeding182** [comment]
Hey :)

Thanks for the feedback

I do not intend to provide support or feature updates on this repository as I simply use it as a playground and showcase for myself. You're welcome to use and modify what you like and start work on a proper library!

**Comment by abdeldjalilfl** [comment]
what is the solution for that @bleeding182  @anasanasanas

**Comment by giacomuzzi** [comment]
Here the solution:
![image](https://user-images.githubusercontent.com/13006878/50794746-bad87900-12aa-11e9-9291-22999290e319.png)
